use_frameworks!

platform :ios, '10.0'

target 'LLNetworkAccessibility-OC_Example' do
  pod 'LLNetworkAccessibility-OC', :path => '../'

  target 'LLNetworkAccessibility-OC_Tests' do
    inherit! :search_paths

    
  end
end
